#!/usr/local/bin/expect -f

set timeout -1

spawn gphotos-uploader-cli --config /config push

expect "Enter the passphrase to open the token store: "
send "$env(CLI_PASSPHRASE)\r"

expect eof